export const musicVideo = [
    {
        id: 1,
        name: "BẢN TÌNH CA MÙA ĐÔNG",
        url: "https://www.youtube.com/embed/Yp4kzdbNuIE",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/1.jpg",
    },
    {
        id: 2,
        name: "ĐÁ LÔNG NHEO",
        url: "https://www.youtube.com/embed/qFFUSveH7VE",
        type: "Offical Music Video",
        singer: "Gusty",
        thumbnail: "/assets/Thumbnail/2.jpg",
    },
    {
        id: 3,
        name: "HÃY VỀ ĐÂY BÊN ANH",
        url: "https://www.youtube.com/embed/fTgsJM_4GjA",
        type: "Music Video",
        singer: "Lien Binh Phat",
        thumbnail: "/assets/Thumbnail/3.jpg",
    },
    {
        id: 4,
        name: "NẤC THANG LÊN THIÊN ĐƯỜNG",
        url: "https://www.youtube.com/embed/foc5tYsyaXU",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/4.jpg",
    },
    {
        id: 5,
        name: "NHƯ MÙA TUYẾT ĐẦU TIÊN",
        url: "https://www.youtube.com/embed/qfdxApg0Z_o",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/5.jpeg",
    },
    {
        id: 6,
        name: "XIN LỖI ANH YÊU EM",
        url: "https://www.youtube.com/embed/9EziZMELz_k",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/6.jpg",    
    },
]

export const musicVideo1 = [
    {
        id: 1,
        name: "BẢN TÌNH CA MÙA ĐÔNG",
        url: "https://www.youtube.com/embed/Yp4kzdbNuIE",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/1.jpg",
    },
    {
        id: 2,
        name: "ĐÁ LÔNG NHEO",
        url: "https://www.youtube.com/embed/qFFUSveH7VE",
        type: "Offical Music Video",
        singer: "Gusty",
        thumbnail: "/assets/Thumbnail/2.jpg",
    },
    {
        id: 3,
        name: "HÃY VỀ ĐÂY BÊN ANH",
        url: "https://www.youtube.com/embed/fTgsJM_4GjA",
        type: "Music Video",
        singer: "Lien Binh Phat",
        thumbnail: "/assets/Thumbnail/3.jpg",
    },
    {
        id: 4,
        name: "NẤC THANG LÊN THIÊN ĐƯỜNG",
        url: "https://www.youtube.com/embed/foc5tYsyaXU",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/4.jpg",
    },
    {
        id: 5,
        name: "NHƯ MÙA TUYẾT ĐẦU TIÊN",
        url: "https://www.youtube.com/embed/qfdxApg0Z_o",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/5.jpeg",
    },
    {
        id: 6,
        name: "XIN LỖI ANH YÊU EM",
        url: "https://www.youtube.com/embed/9EziZMELz_k",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/6.jpg",    
    },
]

export const musicVideo2 = [
    {
        id: 1,
        name: "BẢN TÌNH CA MÙA ĐÔNG",
        url: "https://www.youtube.com/embed/Yp4kzdbNuIE",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/1.jpg",
    },
    {
        id: 2,
        name: "ĐÁ LÔNG NHEO",
        url: "https://www.youtube.com/embed/qFFUSveH7VE",
        type: "Offical Music Video",
        singer: "Gusty",
        thumbnail: "/assets/Thumbnail/2.jpg",
    },
    {
        id: 3,
        name: "HÃY VỀ ĐÂY BÊN ANH",
        url: "https://www.youtube.com/embed/fTgsJM_4GjA",
        type: "Music Video",
        singer: "Lien Binh Phat",
        thumbnail: "/assets/Thumbnail/3.jpg",
    },
    {
        id: 4,
        name: "NẤC THANG LÊN THIÊN ĐƯỜNG",
        url: "https://www.youtube.com/embed/foc5tYsyaXU",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/4.jpg",
    },
    {
        id: 5,
        name: "NHƯ MÙA TUYẾT ĐẦU TIÊN",
        url: "https://www.youtube.com/embed/qfdxApg0Z_o",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/5.jpeg",
    },
    {
        id: 6,
        name: "XIN LỖI ANH YÊU EM",
        url: "https://www.youtube.com/embed/9EziZMELz_k",
        type: "Cover",
        singer: "Mr B",
        thumbnail: "/assets/Thumbnail/6.jpg",    
    },
]